"""
System message detection for WhatsApp .txt exports.

System messages are notifications generated by WhatsApp itself (encryption
notices, group events, etc.). They must be filtered out before analysis.
"""
import re

# Patterns that, when found in the post-timestamp portion, indicate a system message.
# These cover Spanish and English WhatsApp exports.
_SYSTEM_PATTERNS: list[re.Pattern] = [
    # Encryption / security
    re.compile(r"Los mensajes y llamadas están cifrados", re.IGNORECASE),
    re.compile(r"Messages and calls are end-to-end encrypted", re.IGNORECASE),
    re.compile(r"Tu código de seguridad", re.IGNORECASE),
    re.compile(r"Your security code", re.IGNORECASE),
    re.compile(r"cifrado de extremo a extremo", re.IGNORECASE),
    # Group events
    re.compile(r"creó el grupo", re.IGNORECASE),
    re.compile(r"created (the )?group", re.IGNORECASE),
    re.compile(r"añadió a", re.IGNORECASE),
    re.compile(r"added .+? to the group", re.IGNORECASE),
    re.compile(r"salió del grupo", re.IGNORECASE),
    re.compile(r"left the group", re.IGNORECASE),
    re.compile(r"fue eliminado", re.IGNORECASE),
    re.compile(r"was removed", re.IGNORECASE),
    re.compile(r"cambió el asunto del grupo", re.IGNORECASE),
    re.compile(r"changed the group subject", re.IGNORECASE),
    re.compile(r"cambió la descripción del grupo", re.IGNORECASE),
    re.compile(r"cambió el ícono del grupo", re.IGNORECASE),
    re.compile(r"cambió la foto del grupo", re.IGNORECASE),
    re.compile(r"changed this group", re.IGNORECASE),
    # Disappearing messages
    re.compile(r"mensajes temporales", re.IGNORECASE),
    re.compile(r"disappearing messages", re.IGNORECASE),
    re.compile(r"activó los mensajes temporales", re.IGNORECASE),
    re.compile(r"turned on disappearing messages", re.IGNORECASE),
    # Pinned messages
    re.compile(r"fijó un mensaje", re.IGNORECASE),
    re.compile(r"pinned a message", re.IGNORECASE),
    # Ad / Facebook integration
    re.compile(r"Este chat de empresa está vinculado", re.IGNORECASE),
    re.compile(r"This business chat is linked", re.IGNORECASE),
    re.compile(r"proviene de un anuncio de Facebook", re.IGNORECASE),
    re.compile(r"from a Facebook ad", re.IGNORECASE),
    # Missed calls
    re.compile(r"Llamada de voz perdida", re.IGNORECASE),
    re.compile(r"Missed voice call", re.IGNORECASE),
    re.compile(r"Videollamada perdida", re.IGNORECASE),
    re.compile(r"Missed video call", re.IGNORECASE),
    # HTML tags (some exports have these)
    re.compile(r"</?b>", re.IGNORECASE),
    re.compile(r"</?i>", re.IGNORECASE),
    # Contact cards / business info
    re.compile(r"Se compartió la ubicación en vivo", re.IGNORECASE),
    re.compile(r"shared their live location", re.IGNORECASE),
    re.compile(r"dejó de compartir", re.IGNORECASE),
    re.compile(r"stopped sharing", re.IGNORECASE),
    # Number changes
    re.compile(r"cambió su número de teléfono", re.IGNORECASE),
    re.compile(r"changed their phone number", re.IGNORECASE),
    # WhatsApp account
    re.compile(r"Ahora eres administrador", re.IGNORECASE),
    re.compile(r"You're now an admin", re.IGNORECASE),
    re.compile(r"Solo los administradores pueden", re.IGNORECASE),
    re.compile(r"Only admins can", re.IGNORECASE),
    # Payment notifications
    re.compile(r"realizó un pago", re.IGNORECASE),
    re.compile(r"sent a payment", re.IGNORECASE),
]


def is_system_message(text: str) -> bool:
    """
    Return True if the text (post-timestamp, post-separator content) looks like
    a WhatsApp system message that should be filtered out.
    """
    for pattern in _SYSTEM_PATTERNS:
        if pattern.search(text):
            return True
    return False
