"""
Generate a comprehensive demo PDF that exercises every section of the report.

All data is synthetic but runs through the real PDF generation pipeline —
charts, aggregates, health score, funnel, client relationship, WAHA metrics,
response time distribution, quality breakdown, etc.

Usage:
    python scripts/generate_demo_report.py
    # → writes demo_full_report.pdf to the project root
"""

import sys
import os
from datetime import datetime, timedelta
from pathlib import Path

# Run from project root
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.delivery.reports.pdf_generator import generate_pdf_report
from app.models.schemas import ConversationAnalysisResult, QualityBreakdown
from app.models.enums import Sentiment, ConversionStatus

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
BASE = datetime(2026, 5, 1, 9, 0, 0)

_conv_counter = 0


def _cid() -> str:
    global _conv_counter
    _conv_counter += 1
    return f"demo-conv-{_conv_counter:03d}"


def _dt(days: int = 0, hours: int = 0) -> datetime:
    return BASE + timedelta(days=days, hours=hours)


def _make(
    *,
    # identity
    phone: str,
    name: str | None = None,
    started_days: int = 0,
    started_hours: int = 0,
    # core analysis
    sentiment: Sentiment = Sentiment.POSITIVE,
    sentiment_score: float = 0.7,
    sentiment_reason: str = "Cliente satisfecho con la atención recibida.",
    primary_topic: str = "Consulta general",
    secondary_topics: list[str] | None = None,
    quality_score: float = 7.5,
    helpfulness: float = 8.0,
    tone: float = 7.5,
    completeness: float = 7.0,
    conversion_status: ConversionStatus = ConversionStatus.NOT_APPLICABLE,
    conversion_reason: str | None = None,
    summary: str = "Conversación de consulta estándar. El cliente recibió respuesta oportuna.",
    key_points: list[str] | None = None,
    customer_questions: list[str] | None = None,
    # response times
    first_rt: float | None = 180.0,
    avg_rt: float | None = 300.0,
    median_rt: float | None = 280.0,
    p95_rt: float | None = 900.0,
    avg_rt_bh: float | None = 250.0,
    # volume
    total_messages: int = 12,
    inbound: int = 6,
    outbound: int = 6,
    duration_min: float = 35.0,
    unanswered: int = 0,
    trailing_inbound: int = 0,
    response_time_by_hour: dict[str, float] | None = None,
    # WAHA
    delivery_rate: float | None = 98.0,
    read_rate: float | None = 85.0,
    is_ghosted: bool = False,
    last_ack: int | None = 3,
    op_coverage: float | None = 92.0,
    ooh_inbound_pct: float | None = 8.0,
    wa_unread: int | None = 0,
    wa_muted: bool = False,
    wa_archived: bool = False,
    # client relationship
    client_rel: str | None = "returning",
    client_rel_source: str | None = "ai",
    client_rel_signals: list[str] | None = None,
    # funnel
    has_intent: bool = False,
    intent_stage: str | None = None,
    intent_first_at: datetime | None = None,
    quote_requested_at: datetime | None = None,
    quote_sent_at: datetime | None = None,
    quote_rt_seconds: int | None = None,
    followup_count: int | None = None,
    followup_delay_h: float | None = None,
    lost_reason: str | None = None,
    lost_reason_detail: str | None = None,
) -> ConversationAnalysisResult:
    started = _dt(days=started_days, hours=started_hours)
    return ConversationAnalysisResult(
        conversation_id=_cid(),
        contact_phone=phone,
        contact_name=name,
        started_at=started,
        sentiment=sentiment,
        sentiment_score=sentiment_score,
        sentiment_reason=sentiment_reason,
        primary_topic=primary_topic,
        secondary_topics=secondary_topics or [],
        quality_score=quality_score,
        quality_breakdown=QualityBreakdown(
            helpfulness=helpfulness, tone=tone, completeness=completeness
        ),
        conversion_status=conversion_status,
        conversion_reason=conversion_reason,
        summary=summary,
        key_points=key_points or [],
        customer_questions=customer_questions or [],
        first_response_time_seconds=first_rt,
        avg_response_time_seconds=avg_rt,
        median_response_time_seconds=median_rt,
        p95_response_time_seconds=p95_rt,
        avg_response_time_bh_seconds=avg_rt_bh,
        unanswered_count=unanswered,
        trailing_inbound_messages=trailing_inbound,
        total_messages=total_messages,
        inbound_count=inbound,
        outbound_count=outbound,
        duration_minutes=duration_min,
        response_time_by_hour=response_time_by_hour,
        delivery_rate=delivery_rate,
        read_rate=read_rate,
        is_ghosted=is_ghosted,
        last_business_msg_ack=last_ack,
        operational_coverage_score=op_coverage,
        out_of_hours_inbound_pct=ooh_inbound_pct,
        wa_unread_count=wa_unread,
        wa_is_muted=wa_muted,
        wa_is_archived=wa_archived,
        client_relationship=client_rel,
        client_relationship_source=client_rel_source,
        client_relationship_signals=client_rel_signals or [],
        has_purchase_intent=has_intent,
        intent_stage=intent_stage,
        intent_first_at=intent_first_at,
        quote_requested_at=quote_requested_at,
        quote_sent_at=quote_sent_at,
        quote_response_time_seconds=quote_rt_seconds,
        post_quote_followup_count=followup_count,
        followup_delay_hours=followup_delay_h,
        lost_reason=lost_reason,
        lost_reason_detail=lost_reason_detail,
    )


# ---------------------------------------------------------------------------
# Build 35 rich conversations
# ---------------------------------------------------------------------------

HOUR_PATTERN = {
    "8": 420.0, "9": 310.0, "10": 190.0, "11": 160.0,
    "12": 480.0, "13": 520.0, "14": 280.0, "15": 240.0,
    "16": 300.0, "17": 380.0, "18": 700.0,
}

results = [

    # ────────────────────────────────────────────────────────────────────────
    # NEW CLIENTS — first-time, explored and converted
    # ────────────────────────────────────────────────────────────────────────
    _make(
        phone="+573001111001", name="Valentina Torres",
        started_days=0, started_hours=9,
        sentiment=Sentiment.POSITIVE, sentiment_score=0.88,
        sentiment_reason="Muy satisfecha, cerró compra de inmediato.",
        primary_topic="Ortodoncia invisible",
        secondary_topics=["Precios", "Financiación"],
        quality_score=9.2, helpfulness=9.5, tone=9.0, completeness=9.0,
        conversion_status=ConversionStatus.CONVERTED,
        conversion_reason="Cerró cita y pagó anticipo en la misma conversación.",
        summary="Nueva paciente interesada en ortodoncia invisible. Consultó precio, método de pago y tiempo de tratamiento. El asesor respondió con claridad y propuso financiación a 12 cuotas. La paciente confirmó cita.",
        key_points=["Presupuesto aprobado $4.5M", "Inicio tratamiento en 2 semanas", "Financiación 0% interés"],
        customer_questions=["¿Cuánto cuesta la ortodoncia invisible?", "¿Tienen financiación?", "¿Cuánto dura el tratamiento?"],
        first_rt=95.0, avg_rt=185.0, median_rt=170.0, p95_rt=410.0, avg_rt_bh=165.0,
        total_messages=18, inbound=9, outbound=9, duration_min=48.0,
        response_time_by_hour={"14": 185.0, "15": 190.0},
        delivery_rate=100.0, read_rate=100.0, is_ghosted=False, last_ack=4,
        op_coverage=100.0, ooh_inbound_pct=0.0, wa_unread=0,
        client_rel="new", client_rel_source="both",
        client_rel_signals=["Sin historial previo en WAHA", "Primer mensaje dice 'los encontré en Instagram'"],
        has_intent=True, intent_stage="converted",
        intent_first_at=_dt(0, 9), quote_requested_at=_dt(0, 9, ),
        quote_sent_at=_dt(0, 9) + timedelta(minutes=12),
        quote_rt_seconds=720, followup_count=1, followup_delay_h=0.5,
    ),

    _make(
        phone="+573001111002", name="Santiago Ríos",
        started_days=0, started_hours=10,
        sentiment=Sentiment.POSITIVE, sentiment_score=0.82,
        sentiment_reason="Interesado y con buena disposición para agendar.",
        primary_topic="Blanqueamiento dental",
        secondary_topics=["Duración del resultado"],
        quality_score=8.5, helpfulness=8.5, tone=8.5, completeness=8.5,
        conversion_status=ConversionStatus.CONVERTED,
        conversion_reason="Agendó cita de blanqueamiento tras recibir cotización.",
        summary="Paciente nuevo preguntó por blanqueamiento. Asesor explicó técnica de consultorio vs kit casero. Eligió el de consultorio y agendó.",
        key_points=["Blanqueamiento consultorio $800K", "Agendado para próxima semana"],
        customer_questions=["¿Cuánto tiempo dura el blanqueamiento?", "¿Duele?", "¿Diferencia entre casero y consultorio?"],
        first_rt=120.0, avg_rt=240.0, median_rt=220.0, p95_rt=600.0, avg_rt_bh=210.0,
        total_messages=14, inbound=7, outbound=7, duration_min=32.0,
        response_time_by_hour={"10": 240.0, "11": 250.0},
        delivery_rate=100.0, read_rate=100.0, last_ack=4,
        op_coverage=100.0, ooh_inbound_pct=0.0,
        client_rel="new", client_rel_source="ai",
        client_rel_signals=["No hay mensajes anteriores", "Presentación de primera vez"],
        has_intent=True, intent_stage="converted",
        intent_first_at=_dt(0, 10),
        quote_sent_at=_dt(0, 10) + timedelta(minutes=20),
        quote_rt_seconds=1200, followup_count=0,
    ),

    _make(
        phone="+573001111003", name="Camila Herrera",
        started_days=1, started_hours=9,
        sentiment=Sentiment.POSITIVE, sentiment_score=0.79,
        sentiment_reason="Paciente nueva muy entusiasmada con el tratamiento.",
        primary_topic="Ortodoncia metálica",
        quality_score=8.8, helpfulness=9.0, tone=8.5, completeness=9.0,
        conversion_status=ConversionStatus.CONVERTED,
        conversion_reason="Agendó cita de valoración inicial.",
        summary="Consulta para ortodoncia tradicional. Padres preguntaron por opciones para su hija de 14 años. Médico explicó proceso y costos.",
        key_points=["Valoración gratuita agendada", "Paciente menor — requiere presencia de padres"],
        customer_questions=["¿A qué edad se puede poner brackets?", "¿Cuánto tiempo dura el tratamiento en niños?"],
        first_rt=200.0, avg_rt=350.0, median_rt=310.0, p95_rt=800.0, avg_rt_bh=300.0,
        total_messages=16, inbound=8, outbound=8, duration_min=40.0,
        response_time_by_hour={"9": 350.0},
        delivery_rate=99.0, read_rate=92.0, last_ack=4,
        op_coverage=100.0, ooh_inbound_pct=0.0,
        client_rel="new", client_rel_source="both",
        client_rel_signals=["Sin historial WAHA", "Menciona 'los recomendaron'"],
        has_intent=True, intent_stage="converted",
        intent_first_at=_dt(1, 9),
        quote_sent_at=_dt(1, 9) + timedelta(minutes=35),
        quote_rt_seconds=2100, followup_count=2, followup_delay_h=1.0,
    ),

    _make(
        phone="+573001111004", name="Andrés Morales",
        started_days=1, started_hours=11,
        sentiment=Sentiment.POSITIVE, sentiment_score=0.75,
        primary_topic="Implantes dentales",
        quality_score=8.1, helpfulness=8.0, tone=8.5, completeness=8.0,
        conversion_status=ConversionStatus.CONVERTED,
        conversion_reason="Aceptó plan de implante unitario y firmó formulario digital.",
        summary="Paciente nuevo con diente perdido. Consultó sobre implante. Cotización enviada por PDF. Aceptó.",
        customer_questions=["¿Cuánto vale un implante dental?", "¿Cuántas citas son?"],
        first_rt=145.0, avg_rt=290.0, median_rt=270.0, p95_rt=650.0, avg_rt_bh=260.0,
        total_messages=15, inbound=7, outbound=8, duration_min=52.0,
        response_time_by_hour={"11": 290.0, "12": 310.0},
        delivery_rate=100.0, read_rate=95.0, last_ack=4,
        op_coverage=95.0, ooh_inbound_pct=5.0,
        client_rel="new", client_rel_source="ai",
        client_rel_signals=["Primera consulta detectada en texto"],
        has_intent=True, intent_stage="converted",
        intent_first_at=_dt(1, 11),
        quote_requested_at=_dt(1, 11) + timedelta(minutes=5),
        quote_sent_at=_dt(1, 11) + timedelta(minutes=45),
        quote_rt_seconds=2400, followup_count=3, followup_delay_h=2.0,
    ),

    # ────────────────────────────────────────────────────────────────────────
    # RETURNING CLIENTS — existing patients, different stages
    # ────────────────────────────────────────────────────────────────────────
    _make(
        phone="+573002222001", name="María Fernanda Castillo",
        started_days=2, started_hours=8,
        sentiment=Sentiment.POSITIVE, sentiment_score=0.91,
        primary_topic="Control de ortodoncia",
        quality_score=9.0, helpfulness=9.0, tone=9.5, completeness=8.5,
        conversion_status=ConversionStatus.NOT_APPLICABLE,
        summary="Paciente activa en tratamiento, solicitó reprogramar cita de control mensual.",
        customer_questions=["¿Puedo mover mi cita del jueves?"],
        first_rt=60.0, avg_rt=120.0, median_rt=110.0, p95_rt=300.0, avg_rt_bh=100.0,
        total_messages=8, inbound=4, outbound=4, duration_min=15.0,
        response_time_by_hour={"8": 120.0},
        delivery_rate=100.0, read_rate=100.0, last_ack=4,
        op_coverage=100.0, ooh_inbound_pct=0.0,
        client_rel="returning", client_rel_source="both",
        client_rel_signals=["5 citas previas registradas", "Paciente activo en ortodoncia"],
    ),

    _make(
        phone="+573002222002", name="Ricardo Peña",
        started_days=2, started_hours=14,
        sentiment=Sentiment.POSITIVE, sentiment_score=0.85,
        primary_topic="Mantenimiento blanqueamiento",
        quality_score=8.7, helpfulness=9.0, tone=8.5, completeness=8.5,
        conversion_status=ConversionStatus.CONVERTED,
        conversion_reason="Compró kit de mantenimiento en consultorio.",
        summary="Cliente volvió para mantenimiento post-blanqueamiento. Compró el kit de retención recomendado.",
        first_rt=75.0, avg_rt=160.0, median_rt=150.0, p95_rt=380.0, avg_rt_bh=140.0,
        total_messages=10, inbound=5, outbound=5, duration_min=22.0,
        response_time_by_hour={"14": 160.0},
        delivery_rate=100.0, read_rate=98.0, last_ack=4,
        op_coverage=100.0, ooh_inbound_pct=0.0,
        client_rel="returning", client_rel_source="both",
        client_rel_signals=["3 citas previas", "Compró blanqueamiento hace 6 meses"],
        has_intent=True, intent_stage="converted",
        intent_first_at=_dt(2, 14),
        quote_sent_at=_dt(2, 14) + timedelta(minutes=8),
        quote_rt_seconds=480, followup_count=0,
    ),

    _make(
        phone="+573002222003", name="Laura Acosta",
        started_days=3, started_hours=9,
        sentiment=Sentiment.NEUTRAL, sentiment_score=0.5,
        primary_topic="Consulta de segunda opinión",
        quality_score=7.8, helpfulness=8.0, tone=7.5, completeness=8.0,
        conversion_status=ConversionStatus.PENDING,
        conversion_reason="Quiere comparar precios antes de decidir.",
        summary="Paciente conocida solicitó segunda opinión sobre un tratamiento que le recomendaron en otra clínica. Aún evaluando.",
        customer_questions=["¿Qué opina del tratamiento que me recomendaron?", "¿Es necesario extraer las muelas del juicio antes de los brackets?"],
        first_rt=210.0, avg_rt=450.0, median_rt=420.0, p95_rt=1100.0, avg_rt_bh=380.0,
        total_messages=14, inbound=8, outbound=6, duration_min=55.0,
        response_time_by_hour={"9": 450.0, "10": 480.0},
        delivery_rate=98.0, read_rate=90.0, last_ack=3,
        op_coverage=88.0, ooh_inbound_pct=12.0,
        client_rel="returning", client_rel_source="both",
        client_rel_signals=["2 citas previas hace 1 año"],
        has_intent=True, intent_stage="pending",
        intent_first_at=_dt(3, 9),
        quote_requested_at=_dt(3, 9) + timedelta(minutes=30),
        quote_sent_at=_dt(3, 9) + timedelta(hours=2),
        quote_rt_seconds=7200, followup_count=1, followup_delay_h=24.0,
    ),

    _make(
        phone="+573002222004", name="Julián Gómez",
        started_days=3, started_hours=17,
        sentiment=Sentiment.NEGATIVE, sentiment_score=0.22,
        primary_topic="Reclamo por tratamiento",
        quality_score=5.5, helpfulness=6.0, tone=5.0, completeness=5.5,
        conversion_status=ConversionStatus.LOST,
        conversion_reason="Paciente insatisfecho, decidió no continuar el tratamiento.",
        summary="Paciente se queja de molestias persistentes tras ajuste de brackets. Expresó frustración por los tiempos de respuesta. El asesor tardó más de 2h en responder.",
        customer_questions=["¿Es normal que me duela tanto después del ajuste?", "¿Por qué tardaron tanto en contestarme?"],
        first_rt=7800.0, avg_rt=3600.0, median_rt=3400.0, p95_rt=8000.0, avg_rt_bh=3200.0,
        total_messages=20, inbound=12, outbound=8, duration_min=75.0,
        response_time_by_hour={"17": 3600.0, "18": 3800.0},
        delivery_rate=96.0, read_rate=72.0, last_ack=3,
        op_coverage=60.0, ooh_inbound_pct=35.0,
        client_rel="returning", client_rel_source="both",
        client_rel_signals=["4 citas previas", "En tratamiento activo"],
    ),

    # ────────────────────────────────────────────────────────────────────────
    # FUNNEL HEAVY — quote requested, negotiating, exploring, lost (various)
    # ────────────────────────────────────────────────────────────────────────
    _make(
        phone="+573003333001", name="Sofía Ramírez",
        started_days=4, started_hours=10,
        sentiment=Sentiment.POSITIVE, sentiment_score=0.80,
        primary_topic="Carillas de porcelana",
        secondary_topics=["Financiación", "Tiempo de fabricación"],
        quality_score=8.3, helpfulness=8.5, tone=8.0, completeness=8.5,
        conversion_status=ConversionStatus.PENDING,
        conversion_reason="Revisando opciones de pago.",
        summary="Paciente nueva muy interesada en carillas de porcelana para mejorar su sonrisa. Solicitó cotización detallada. Está comparando con otra clínica.",
        customer_questions=["¿Cuánto cuestan las carillas de porcelana?", "¿Se pueden hacer de 6 dientes solamente?", "¿Cuántas sesiones son?"],
        first_rt=180.0, avg_rt=360.0, median_rt=330.0, p95_rt=850.0, avg_rt_bh=310.0,
        total_messages=22, inbound=12, outbound=10, duration_min=68.0,
        response_time_by_hour={"10": 360.0, "11": 350.0},
        delivery_rate=100.0, read_rate=95.0, last_ack=4,
        op_coverage=90.0, ooh_inbound_pct=10.0,
        client_rel="new", client_rel_source="ai",
        client_rel_signals=["No tiene historial previo"],
        has_intent=True, intent_stage="quoted",
        intent_first_at=_dt(4, 10),
        quote_requested_at=_dt(4, 10) + timedelta(minutes=20),
        quote_sent_at=_dt(4, 10) + timedelta(minutes=55),
        quote_rt_seconds=2100, followup_count=2, followup_delay_h=4.0,
    ),

    _make(
        phone="+573003333002", name="Diego Salinas",
        started_days=4, started_hours=15,
        sentiment=Sentiment.NEUTRAL, sentiment_score=0.55,
        primary_topic="Implantes dentales",
        secondary_topics=["Garantía", "Marca del implante"],
        quality_score=7.9, helpfulness=8.0, tone=7.5, completeness=8.0,
        conversion_status=ConversionStatus.PENDING,
        conversion_reason="Evaluando opciones de implante antes de decidir.",
        summary="Consulta detallada sobre implantes. Comparó precios de tres marcas. Asesor envió comparativo técnico. Diego está en proceso de decidir.",
        customer_questions=["¿Qué marca de implante usan?", "¿Tienen garantía los implantes?", "¿Qué pasa si falla el implante?"],
        first_rt=320.0, avg_rt=580.0, median_rt=550.0, p95_rt=1400.0, avg_rt_bh=500.0,
        total_messages=26, inbound=14, outbound=12, duration_min=90.0,
        response_time_by_hour={"15": 580.0, "16": 600.0},
        delivery_rate=98.0, read_rate=88.0, last_ack=3,
        op_coverage=85.0, ooh_inbound_pct=15.0,
        client_rel="new", client_rel_source="ai",
        client_rel_signals=["Primera vez consultando"],
        has_intent=True, intent_stage="negotiating",
        intent_first_at=_dt(4, 15),
        quote_requested_at=_dt(4, 15) + timedelta(minutes=45),
        quote_sent_at=_dt(4, 15) + timedelta(hours=3),
        quote_rt_seconds=10800, followup_count=4, followup_delay_h=48.0,
    ),

    _make(
        phone="+573003333003", name="Natalia Ospina",
        started_days=5, started_hours=9,
        sentiment=Sentiment.POSITIVE, sentiment_score=0.78,
        primary_topic="Ortodoncia invisible",
        quality_score=8.6, helpfulness=9.0, tone=8.5, completeness=8.5,
        conversion_status=ConversionStatus.PENDING,
        conversion_reason="Interesada pero no ha dado respuesta definitiva.",
        summary="Interesada en Invisalign. Recibió cotización completa. No ha dado respuesta final.",
        customer_questions=["¿Tienen Invisalign?", "¿Cuánto cuesta Invisalign vs brackets?"],
        first_rt=150.0, avg_rt=280.0, median_rt=260.0, p95_rt=700.0, avg_rt_bh=240.0,
        total_messages=18, inbound=10, outbound=8, duration_min=45.0,
        response_time_by_hour={"9": 280.0},
        delivery_rate=99.0, read_rate=91.0, last_ack=4,
        op_coverage=88.0, ooh_inbound_pct=12.0,
        client_rel="new", client_rel_source="ai",
        client_rel_signals=["Primera interacción"],
        has_intent=True, intent_stage="quote_requested",
        intent_first_at=_dt(5, 9),
        quote_requested_at=_dt(5, 9) + timedelta(minutes=15),
        quote_sent_at=_dt(5, 9) + timedelta(minutes=35),
        quote_rt_seconds=1200, followup_count=1, followup_delay_h=6.0,
    ),

    _make(
        phone="+573003333004", name="Felipe Moreno",
        started_days=5, started_hours=16,
        sentiment=Sentiment.NEUTRAL, sentiment_score=0.48,
        primary_topic="Diseño de sonrisa",
        quality_score=7.5, helpfulness=7.5, tone=7.5, completeness=7.5,
        conversion_status=ConversionStatus.LOST,
        conversion_reason="Precio demasiado alto para su presupuesto.",
        summary="Muy interesado en diseño de sonrisa completo (carillas + blanqueamiento). Después de recibir cotización de $18M, decidió no continuar.",
        customer_questions=["¿Qué incluye el diseño de sonrisa completo?", "¿Tienen algún plan de pago especial?"],
        first_rt=240.0, avg_rt=500.0, median_rt=470.0, p95_rt=1200.0, avg_rt_bh=440.0,
        total_messages=20, inbound=11, outbound=9, duration_min=65.0,
        response_time_by_hour={"16": 500.0, "17": 520.0},
        delivery_rate=97.0, read_rate=85.0, last_ack=3,
        op_coverage=82.0, ooh_inbound_pct=18.0,
        client_rel="new", client_rel_source="ai",
        client_rel_signals=["Primera consulta"],
        has_intent=True, intent_stage="lost",
        intent_first_at=_dt(5, 16),
        quote_requested_at=_dt(5, 16) + timedelta(minutes=30),
        quote_sent_at=_dt(5, 16) + timedelta(hours=1),
        quote_rt_seconds=3600, followup_count=2, followup_delay_h=3.0,
        lost_reason="price",
        lost_reason_detail="El cliente indicó que el presupuesto de $18M supera ampliamente su límite de $8M. No tiene acceso a financiación.",
    ),

    _make(
        phone="+573003333005", name="Isabela Vargas",
        started_days=6, started_hours=11,
        sentiment=Sentiment.NEGATIVE, sentiment_score=0.18,
        primary_topic="Carillas de porcelana",
        quality_score=6.8, helpfulness=7.0, tone=6.5, completeness=7.0,
        conversion_status=ConversionStatus.LOST,
        conversion_reason="Eligió otra clínica.",
        summary="Estaba muy interesada pero mencionó que otra clínica le ofreció el mismo tratamiento más económico y con mejor garantía.",
        customer_questions=["¿Por qué sus precios son más altos que en otras clínicas?"],
        first_rt=420.0, avg_rt=900.0, median_rt=860.0, p95_rt=2100.0, avg_rt_bh=800.0,
        total_messages=16, inbound=9, outbound=7, duration_min=58.0,
        response_time_by_hour={"11": 900.0, "12": 950.0},
        delivery_rate=95.0, read_rate=80.0, last_ack=3,
        op_coverage=75.0, ooh_inbound_pct=25.0,
        client_rel="new", client_rel_source="ai",
        client_rel_signals=["Primera vez"],
        has_intent=True, intent_stage="lost",
        intent_first_at=_dt(6, 11),
        quote_requested_at=_dt(6, 11) + timedelta(minutes=25),
        quote_sent_at=_dt(6, 11) + timedelta(hours=2, minutes=30),
        quote_rt_seconds=9000, followup_count=1, followup_delay_h=1.0,
        lost_reason="competition",
        lost_reason_detail="La paciente encontró la misma carilla en otra clínica a $1.2M menos por unidad, con garantía de 10 años vs 5 años de esta clínica.",
    ),

    _make(
        phone="+573003333006", name="Tomás Jiménez",
        started_days=6, started_hours=14,
        sentiment=Sentiment.POSITIVE, sentiment_score=0.72,
        primary_topic="Ortodoncia invisible",
        quality_score=8.0, helpfulness=8.0, tone=8.0, completeness=8.0,
        conversion_status=ConversionStatus.PENDING,
        conversion_reason="En proceso de aprobación de crédito.",
        summary="Interesado en Invisalign pero está tramitando un crédito con el banco. Asesor registró el seguimiento para la semana siguiente.",
        first_rt=190.0, avg_rt=380.0, median_rt=360.0, p95_rt=900.0, avg_rt_bh=340.0,
        total_messages=16, inbound=9, outbound=7, duration_min=42.0,
        response_time_by_hour={"14": 380.0},
        delivery_rate=99.0, read_rate=93.0, last_ack=4,
        op_coverage=87.0, ooh_inbound_pct=13.0,
        client_rel="new", client_rel_source="ai",
        has_intent=True, intent_stage="pending",
        intent_first_at=_dt(6, 14),
        quote_sent_at=_dt(6, 14) + timedelta(minutes=40),
        quote_rt_seconds=2400, followup_count=2, followup_delay_h=8.0,
    ),

    _make(
        phone="+573003333007", name="Valentina Aguilar",
        started_days=7, started_hours=9,
        sentiment=Sentiment.POSITIVE, sentiment_score=0.77,
        primary_topic="Blanqueamiento dental",
        quality_score=8.2, helpfulness=8.5, tone=8.0, completeness=8.0,
        conversion_status=ConversionStatus.PENDING,
        conversion_reason="Quiere hacerlo después del matrimonio.",
        summary="Paciente planea blanqueamiento para boda en 3 meses. Recibió cotización y fecha tentativa. Aún no confirma.",
        first_rt=210.0, avg_rt=400.0, median_rt=370.0, p95_rt=950.0,
        total_messages=12, inbound=6, outbound=6, duration_min=30.0,
        response_time_by_hour={"9": 400.0},
        delivery_rate=100.0, read_rate=94.0, last_ack=4,
        op_coverage=91.0, ooh_inbound_pct=9.0,
        client_rel="new", client_rel_source="ai",
        has_intent=True, intent_stage="exploring",
        intent_first_at=_dt(7, 9),
    ),

    # ────────────────────────────────────────────────────────────────────────
    # UNANSWERED / GHOSTED / PROBLEMATIC
    # ────────────────────────────────────────────────────────────────────────
    _make(
        phone="+573004444001", name="Carlos Mendoza",
        started_days=7, started_hours=19,
        sentiment=Sentiment.NEUTRAL, sentiment_score=0.5,
        primary_topic="Extracción de muela del juicio",
        quality_score=None,
        conversion_status=ConversionStatus.NOT_APPLICABLE,
        summary="Mensaje recibido a las 7pm. El cliente no recibió respuesta ese día.",
        customer_questions=["¿Cuánto cuesta sacar la muela del juicio?", "¿Aplican anestesia?"],
        first_rt=None, avg_rt=None, median_rt=None,
        total_messages=3, inbound=3, outbound=0, duration_min=0.0,
        unanswered=1, trailing_inbound=3,
        delivery_rate=None, read_rate=None, last_ack=None,
        op_coverage=0.0, ooh_inbound_pct=100.0, wa_unread=3,
        client_rel="uncertain", client_rel_source="ai",
    ),

    _make(
        phone="+573004444002", name="Paola Ríos",
        started_days=8, started_hours=7,
        sentiment=Sentiment.NEUTRAL, sentiment_score=0.5,
        primary_topic="Cita de urgencia",
        quality_score=None,
        conversion_status=ConversionStatus.NOT_APPLICABLE,
        summary="Paciente reportó dolor de muela muy temprano. No hubo respuesta durante horario no hábil.",
        customer_questions=["Tengo un dolor horrible, ¿atienden urgencias?"],
        first_rt=None, avg_rt=None, median_rt=None,
        total_messages=2, inbound=2, outbound=0, duration_min=0.0,
        unanswered=1, trailing_inbound=2,
        delivery_rate=None, read_rate=None, last_ack=None,
        op_coverage=0.0, ooh_inbound_pct=100.0, wa_unread=2,
        client_rel="uncertain", client_rel_source="ai",
    ),

    _make(
        phone="+573004444003", name="Jorge Hernández",
        started_days=8, started_hours=15,
        sentiment=Sentiment.NEGATIVE, sentiment_score=0.15,
        primary_topic="Reclamo de garantía",
        quality_score=4.5, helpfulness=5.0, tone=4.0, completeness=4.5,
        conversion_status=ConversionStatus.LOST,
        conversion_reason="El cliente exigió reembolso y no fue atendido correctamente.",
        summary="Paciente reclamó por relleno que se cayó a los 3 meses. El asesor tardó 45 minutos y no ofreció solución clara. Cliente se fue molesto.",
        customer_questions=["¿Tienen garantía en los tratamientos?", "¿Quién responde por esto?"],
        first_rt=2700.0, avg_rt=1800.0, median_rt=1700.0, p95_rt=3500.0, avg_rt_bh=1600.0,
        total_messages=18, inbound=11, outbound=7, duration_min=80.0,
        response_time_by_hour={"15": 2700.0, "16": 1800.0},
        delivery_rate=94.0, read_rate=78.0, last_ack=2,
        op_coverage=62.0, ooh_inbound_pct=38.0,
        client_rel="returning", client_rel_source="both",
        client_rel_signals=["3 tratamientos previos"],
        is_ghosted=True,
    ),

    _make(
        phone="+573004444004",
        started_days=9, started_hours=13,
        sentiment=Sentiment.NEUTRAL, sentiment_score=0.5,
        primary_topic="Consulta general",
        quality_score=None,
        conversion_status=ConversionStatus.NOT_APPLICABLE,
        summary="Mensaje de texto ilegible. Sin respuesta.",
        first_rt=None, avg_rt=None, median_rt=None,
        total_messages=1, inbound=1, outbound=0, duration_min=0.0,
        unanswered=1, trailing_inbound=1,
        delivery_rate=None, read_rate=None, last_ack=None,
        op_coverage=0.0, ooh_inbound_pct=0.0, wa_unread=1,
        client_rel="uncertain", client_rel_source="ai",
    ),

    # ────────────────────────────────────────────────────────────────────────
    # NORMAL / ROUTINE — various topics, mid-quality
    # ────────────────────────────────────────────────────────────────────────
    _make(
        phone="+573005555001", name="Mariana Castro",
        started_days=2, started_hours=11,
        sentiment=Sentiment.POSITIVE, sentiment_score=0.74,
        primary_topic="Cita de limpieza dental",
        quality_score=8.0, helpfulness=8.0, tone=8.5, completeness=7.5,
        conversion_status=ConversionStatus.CONVERTED,
        conversion_reason="Agendó limpieza rutinaria.",
        summary="Paciente llamó para agendar limpieza semestral. Rápida y satisfactoria.",
        customer_questions=["¿Cuánto cuesta la limpieza dental?", "¿Cada cuánto se recomienda?"],
        first_rt=90.0, avg_rt=180.0, median_rt=165.0, p95_rt=420.0, avg_rt_bh=155.0,
        total_messages=8, inbound=4, outbound=4, duration_min=18.0,
        response_time_by_hour={"11": 180.0},
        delivery_rate=100.0, read_rate=100.0, last_ack=4,
        op_coverage=100.0, ooh_inbound_pct=0.0,
        client_rel="returning", client_rel_source="both",
        client_rel_signals=["Limpieza anterior hace 6 meses"],
    ),

    _make(
        phone="+573005555002", name="Alejandro Pinto",
        started_days=2, started_hours=16,
        sentiment=Sentiment.NEUTRAL, sentiment_score=0.55,
        primary_topic="Consulta sobre seguro médico",
        quality_score=7.2, helpfulness=7.5, tone=7.0, completeness=7.0,
        conversion_status=ConversionStatus.NOT_APPLICABLE,
        summary="Paciente preguntó qué seguros aceptan. El asesor respondió con la lista. No agendó cita.",
        customer_questions=["¿Aceptan Sura?", "¿Con qué EPS trabajan?"],
        first_rt=280.0, avg_rt=520.0, median_rt=490.0, p95_rt=1300.0, avg_rt_bh=460.0,
        total_messages=10, inbound=6, outbound=4, duration_min=28.0,
        response_time_by_hour={"16": 520.0},
        delivery_rate=97.0, read_rate=85.0, last_ack=3,
        op_coverage=84.0, ooh_inbound_pct=16.0,
        client_rel="uncertain", client_rel_source="ai",
    ),

    _make(
        phone="+573005555003", name="Lorena Medina",
        started_days=3, started_hours=10,
        sentiment=Sentiment.POSITIVE, sentiment_score=0.80,
        primary_topic="Ortodoncia invisible",
        quality_score=8.4, helpfulness=8.5, tone=8.5, completeness=8.0,
        conversion_status=ConversionStatus.CONVERTED,
        conversion_reason="Agendó valoración inicial.",
        summary="Paciente referida por una amiga. Quería saber si era candidata para Invisalign. Agendó valoración.",
        customer_questions=["¿Todas las personas pueden usar Invisalign?", "¿Qué tan visible es el alineador?"],
        first_rt=130.0, avg_rt=260.0, median_rt=240.0, p95_rt=620.0, avg_rt_bh=220.0,
        total_messages=12, inbound=6, outbound=6, duration_min=32.0,
        response_time_by_hour={"10": 260.0},
        delivery_rate=100.0, read_rate=97.0, last_ack=4,
        op_coverage=95.0, ooh_inbound_pct=5.0,
        client_rel="new", client_rel_source="ai",
        client_rel_signals=["Referida por contacto existente"],
    ),

    _make(
        phone="+573005555004", name="David Álvarez",
        started_days=4, started_hours=9,
        sentiment=Sentiment.POSITIVE, sentiment_score=0.76,
        primary_topic="Endodoncia",
        quality_score=8.1, helpfulness=8.0, tone=8.5, completeness=7.5,
        conversion_status=ConversionStatus.CONVERTED,
        conversion_reason="Agendó cita de urgencia.",
        summary="Dolor agudo en molar. Asesor identificó necesidad de endodoncia urgente y agendó para el mismo día.",
        customer_questions=["¿Tienen citas para el mismo día?", "¿Cuánto cuesta una endodoncia?"],
        first_rt=85.0, avg_rt=170.0, median_rt=160.0, p95_rt=400.0, avg_rt_bh=150.0,
        total_messages=10, inbound=5, outbound=5, duration_min=22.0,
        response_time_by_hour={"9": 170.0},
        delivery_rate=100.0, read_rate=100.0, last_ack=4,
        op_coverage=100.0, ooh_inbound_pct=0.0,
        client_rel="uncertain", client_rel_source="ai",
    ),

    _make(
        phone="+573005555005", name="Elena Ruiz",
        started_days=5, started_hours=15,
        sentiment=Sentiment.NEUTRAL, sentiment_score=0.52,
        primary_topic="Consulta de precios",
        quality_score=7.0, helpfulness=7.0, tone=7.0, completeness=7.0,
        conversion_status=ConversionStatus.NOT_APPLICABLE,
        summary="Solicitud de lista de precios general. El asesor envió el PDF de tarifas.",
        customer_questions=["¿Tienen catálogo de precios?"],
        first_rt=350.0, avg_rt=600.0, median_rt=570.0, p95_rt=1500.0, avg_rt_bh=530.0,
        total_messages=6, inbound=3, outbound=3, duration_min=15.0,
        response_time_by_hour={"15": 600.0},
        delivery_rate=96.0, read_rate=83.0, last_ack=3,
        op_coverage=80.0, ooh_inbound_pct=20.0,
        client_rel="uncertain", client_rel_source="ai",
    ),

    _make(
        phone="+573005555006", name="Miguel Torres",
        started_days=6, started_hours=10,
        sentiment=Sentiment.POSITIVE, sentiment_score=0.81,
        primary_topic="Control post-operatorio",
        quality_score=8.5, helpfulness=8.5, tone=9.0, completeness=8.0,
        conversion_status=ConversionStatus.NOT_APPLICABLE,
        summary="Paciente post-implante con preguntas sobre cuidados. El asesor respondió con instrucciones claras.",
        customer_questions=["¿Puedo comer sólidos ya?", "¿Cuándo se quita el hilo?"],
        first_rt=65.0, avg_rt=130.0, median_rt=120.0, p95_rt=310.0, avg_rt_bh=110.0,
        total_messages=10, inbound=5, outbound=5, duration_min=20.0,
        response_time_by_hour={"10": 130.0},
        delivery_rate=100.0, read_rate=100.0, last_ack=4,
        op_coverage=100.0, ooh_inbound_pct=0.0,
        client_rel="returning", client_rel_source="both",
        client_rel_signals=["Tratamiento de implante hace 5 días"],
    ),

    _make(
        phone="+573005555007", name="Gabriela López",
        started_days=7, started_hours=14,
        sentiment=Sentiment.POSITIVE, sentiment_score=0.83,
        primary_topic="Blanqueamiento dental",
        quality_score=8.7, helpfulness=9.0, tone=8.5, completeness=8.5,
        conversion_status=ConversionStatus.CONVERTED,
        conversion_reason="Compró el servicio de blanqueamiento.",
        summary="Consulta rápida para blanqueamiento. Precio aceptado al primer intento.",
        customer_questions=["¿Pueden atenderme este fin de semana?"],
        first_rt=110.0, avg_rt=220.0, median_rt=200.0, p95_rt=520.0, avg_rt_bh=185.0,
        total_messages=8, inbound=4, outbound=4, duration_min=18.0,
        response_time_by_hour={"14": 220.0},
        delivery_rate=100.0, read_rate=100.0, last_ack=4,
        op_coverage=100.0, ooh_inbound_pct=0.0,
        client_rel="returning", client_rel_source="both",
        client_rel_signals=["1 cita previa hace 1 año"],
    ),

    _make(
        phone="+573005555008", name="Nicolás Herrera",
        started_days=8, started_hours=11,
        sentiment=Sentiment.NEUTRAL, sentiment_score=0.56,
        primary_topic="Consulta de horarios",
        quality_score=7.3, helpfulness=7.5, tone=7.0, completeness=7.5,
        conversion_status=ConversionStatus.NOT_APPLICABLE,
        summary="Solo quería saber horarios de atención. No agendó.",
        customer_questions=["¿Hasta qué hora atienden?", "¿Abren los sábados?"],
        first_rt=170.0, avg_rt=340.0, median_rt=315.0, p95_rt=780.0, avg_rt_bh=295.0,
        total_messages=6, inbound=4, outbound=2, duration_min=10.0,
        response_time_by_hour={"11": 340.0},
        delivery_rate=98.0, read_rate=89.0, last_ack=3,
        op_coverage=86.0, ooh_inbound_pct=14.0,
        client_rel="uncertain", client_rel_source="ai",
    ),

    _make(
        phone="+573005555009", name="Ana Lucía Gómez",
        started_days=9, started_hours=9,
        sentiment=Sentiment.POSITIVE, sentiment_score=0.87,
        primary_topic="Limpieza dental",
        quality_score=9.1, helpfulness=9.5, tone=9.0, completeness=9.0,
        conversion_status=ConversionStatus.CONVERTED,
        conversion_reason="Agendó y pagó limpieza + fluorización.",
        summary="Excelente atención. Paciente fiel que agenda cada 6 meses. Compró combo limpieza + fluorización.",
        customer_questions=["¿Siguen teniendo el combo de limpieza + flúor?"],
        first_rt=50.0, avg_rt=100.0, median_rt=95.0, p95_rt=240.0, avg_rt_bh=90.0,
        total_messages=8, inbound=4, outbound=4, duration_min=14.0,
        response_time_by_hour={"9": 100.0},
        delivery_rate=100.0, read_rate=100.0, last_ack=4,
        op_coverage=100.0, ooh_inbound_pct=0.0,
        client_rel="returning", client_rel_source="both",
        client_rel_signals=["8 citas previas", "Paciente desde 2022"],
    ),

    _make(
        phone="+573005555010", name="Sebastián Cruz",
        started_days=9, started_hours=16,
        sentiment=Sentiment.POSITIVE, sentiment_score=0.73,
        primary_topic="Ortodoncia metálica",
        quality_score=8.0, helpfulness=8.0, tone=8.0, completeness=8.0,
        conversion_status=ConversionStatus.PENDING,
        conversion_reason="Esperando confirmación del esposo para proceder.",
        summary="Madre consultando para su hijo. Recibió información completa. Necesita consultar con su cónyuge.",
        customer_questions=["¿Incluyen las citas de control en el precio?", "¿Cuántas citas son en total?"],
        first_rt=200.0, avg_rt=400.0, median_rt=370.0, p95_rt=950.0, avg_rt_bh=350.0,
        total_messages=14, inbound=8, outbound=6, duration_min=40.0,
        response_time_by_hour={"16": 400.0},
        delivery_rate=99.0, read_rate=92.0, last_ack=4,
        op_coverage=89.0, ooh_inbound_pct=11.0,
        client_rel="new", client_rel_source="ai",
        has_intent=True, intent_stage="exploring",
        intent_first_at=_dt(9, 16),
    ),

    # ────────────────────────────────────────────────────────────────────────
    # INTERNAL / PROVEEDOR
    # ────────────────────────────────────────────────────────────────────────
    _make(
        phone="+573009999001", name="Proveedor Lab Dental S.A.S",
        started_days=3, started_hours=8,
        sentiment=Sentiment.NEUTRAL, sentiment_score=0.6,
        primary_topic="Coordinación con laboratorio",
        quality_score=None,
        conversion_status=ConversionStatus.NOT_APPLICABLE,
        summary="El laboratorio confirmó la entrega de dos coronas para el día jueves.",
        first_rt=180.0, avg_rt=300.0, median_rt=280.0, p95_rt=700.0, avg_rt_bh=260.0,
        total_messages=10, inbound=5, outbound=5, duration_min=25.0,
        delivery_rate=100.0, read_rate=100.0, last_ack=4,
        op_coverage=None, ooh_inbound_pct=None,
        client_rel="internal", client_rel_source="ai",
        client_rel_signals=["Nombre contiene 'Lab'", "Conversación de coordinación de pedidos"],
    ),

    _make(
        phone="+573009999002", name="Dr. Hernán Suárez (Colega)",
        started_days=5, started_hours=12,
        sentiment=Sentiment.POSITIVE, sentiment_score=0.75,
        primary_topic="Referidos entre colegas",
        quality_score=None,
        conversion_status=ConversionStatus.NOT_APPLICABLE,
        summary="Colega remite paciente para implante. Coordina los datos del caso.",
        first_rt=240.0, avg_rt=480.0, median_rt=450.0, p95_rt=1100.0, avg_rt_bh=420.0,
        total_messages=8, inbound=4, outbound=4, duration_min=20.0,
        delivery_rate=100.0, read_rate=100.0, last_ack=4,
        op_coverage=None, ooh_inbound_pct=None,
        client_rel="internal", client_rel_source="ai",
        client_rel_signals=["Conversación de tipo profesional/coordinación"],
    ),

    # ────────────────────────────────────────────────────────────────────────
    # ADDITIONAL LOST (price-related) with fast response but still lost
    # ────────────────────────────────────────────────────────────────────────
    _make(
        phone="+573006666001", name="Cristina Vargas",
        started_days=10, started_hours=10,
        sentiment=Sentiment.NEGATIVE, sentiment_score=0.25,
        primary_topic="Implantes dentales",
        quality_score=6.5, helpfulness=7.0, tone=6.0, completeness=6.5,
        conversion_status=ConversionStatus.LOST,
        conversion_reason="No contó con el presupuesto suficiente.",
        summary="Quería varios implantes pero el presupuesto total superó sus posibilidades. El asesor no ofreció alternativas.",
        customer_questions=["¿Pueden hacer un plan para 4 implantes?"],
        first_rt=860.0, avg_rt=1500.0, median_rt=1400.0, p95_rt=3600.0, avg_rt_bh=1300.0,
        total_messages=14, inbound=8, outbound=6, duration_min=55.0,
        response_time_by_hour={"10": 1500.0, "11": 1600.0},
        delivery_rate=92.0, read_rate=70.0, last_ack=2,
        op_coverage=68.0, ooh_inbound_pct=32.0,
        client_rel="new", client_rel_source="ai",
        has_intent=True, intent_stage="lost",
        intent_first_at=_dt(10, 10),
        quote_requested_at=_dt(10, 10) + timedelta(minutes=20),
        quote_sent_at=_dt(10, 10) + timedelta(hours=4),
        quote_rt_seconds=14400, followup_count=0,
        lost_reason="price",
        lost_reason_detail="Necesitaba 4 implantes ($32M total). Solo contaba con $12M disponibles y no calificó para crédito.",
    ),

    _make(
        phone="+573006666002", name="Roberto Nieto",
        started_days=11, started_hours=15,
        sentiment=Sentiment.NEUTRAL, sentiment_score=0.42,
        primary_topic="Ortodoncia invisible",
        quality_score=7.0, helpfulness=7.0, tone=7.5, completeness=6.5,
        conversion_status=ConversionStatus.LOST,
        conversion_reason="Decidió no continuar.",
        summary="Empezó a preguntar por Invisalign pero perdió interés después de conocer el costo total y el tiempo de tratamiento.",
        first_rt=540.0, avg_rt=950.0, median_rt=900.0, p95_rt=2200.0, avg_rt_bh=850.0,
        total_messages=12, inbound=7, outbound=5, duration_min=42.0,
        response_time_by_hour={"15": 950.0, "16": 980.0},
        delivery_rate=93.0, read_rate=75.0, last_ack=2,
        op_coverage=72.0, ooh_inbound_pct=28.0,
        client_rel="new", client_rel_source="ai",
        has_intent=True, intent_stage="lost",
        intent_first_at=_dt(11, 15),
        quote_sent_at=_dt(11, 15) + timedelta(hours=1),
        quote_rt_seconds=3600, followup_count=1, followup_delay_h=12.0,
        lost_reason="timing",
        lost_reason_detail="El tiempo de 18-24 meses de tratamiento era demasiado para sus planes de boda en 8 meses.",
    ),

]


# ---------------------------------------------------------------------------
# Previous-report data for comparison block
# ---------------------------------------------------------------------------
_prev = [
    _make(
        phone="+573099001", name="Ref1",
        started_days=-15,
        sentiment=Sentiment.POSITIVE, quality_score=7.2,
        first_rt=250.0, avg_rt=480.0, median_rt=450.0,
        total_messages=12, inbound=6, outbound=6, duration_min=30.0,
        conversion_status=ConversionStatus.CONVERTED,
        client_rel="new",
    ),
    _make(
        phone="+573099002", name="Ref2",
        started_days=-14,
        sentiment=Sentiment.NEUTRAL, quality_score=6.8,
        first_rt=400.0, avg_rt=700.0, median_rt=660.0,
        total_messages=10, inbound=5, outbound=5, duration_min=25.0,
        conversion_status=ConversionStatus.PENDING,
        client_rel="returning",
    ),
    _make(
        phone="+573099003", name="Ref3",
        started_days=-13,
        sentiment=Sentiment.NEGATIVE, quality_score=5.5,
        first_rt=1800.0, avg_rt=2500.0, median_rt=2400.0,
        total_messages=16, inbound=9, outbound=7, duration_min=50.0,
        conversion_status=ConversionStatus.LOST,
        client_rel="returning",
    ),
    _make(
        phone="+573099004", name="Ref4",
        started_days=-12,
        sentiment=Sentiment.POSITIVE, quality_score=7.9,
        first_rt=160.0, avg_rt=320.0, median_rt=300.0,
        total_messages=8, inbound=4, outbound=4, duration_min=18.0,
        conversion_status=ConversionStatus.NOT_APPLICABLE,
        client_rel="new",
    ),
    _make(
        phone="+573099005", name="Ref5",
        started_days=-11,
        sentiment=Sentiment.POSITIVE, quality_score=8.1,
        first_rt=140.0, avg_rt=280.0, median_rt=260.0,
        total_messages=10, inbound=5, outbound=5, duration_min=22.0,
        conversion_status=ConversionStatus.CONVERTED,
        client_rel="new",
    ),
]


# ---------------------------------------------------------------------------
# Generate the PDF
# ---------------------------------------------------------------------------
print(f"Building demo report with {len(results)} conversations...")

pdf_bytes = generate_pdf_report(
    results=results,
    business_name="Clínica Dental Sonrisa Perfecta",
    job_id="demo-full-2026-05-13",
    files_processed=len(results),
    ai_model="claude-sonnet-4-6",
    average_transaction_value=2_500_000.0,   # COP $2.5M por transacción promedio
    business_type="clínica dental / salud",
    is_subscribed=True,
    account_name="sonrisaperfectamed",
    previous_results=_prev,
    previous_job_created_at=datetime(2026, 4, 15, 10, 0, 0),
)

out_path = Path(__file__).resolve().parent.parent / "demo_full_report.pdf"
out_path.write_bytes(pdf_bytes)
print(f"✓ Saved {len(pdf_bytes) / 1024:.0f} KB → {out_path}")
